name: Build Android APK

on:
  push:        # Runs when you push commits to any branch
    branches:
      - '**'
  workflow_dispatch:   # Allows manual runs from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-11-jdk python3-setuptools python3-venv
          pip install --upgrade pip
          pip install Cython
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BRS-Launcher
          path: bin/*.apk

